language: rust
sudo: false

cache:
  directories:
      - target

rust:
  - 1.0.0
  - nightly
  - beta

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo doc &&
      echo "Testing README" &&
      rustdoc --test README.md -L dependency=./target/debug/deps --extern nickel=./target/debug/libnickel.rlib

after_success:
  - |
      (echo "docs.nickel.rs" > target/doc/CNAME) &&
      travis-cargo --only 1.0.0 doc-upload

env:
  global:
    secure: nPXTdkq9TK4LmqJWqB4jxscDG1mnqJzO0UX5ni+oC0SohjgBxdWjbvJ8Kthk3c8Qg/2zGlCryuT1lV4TcD3jF86MHlRlXsO3G8fCbEGdLLzppbV0A2VnEw1knhv2mfUhxA8hsFJE2ncT5qeOVyQ6N3PAMGoYkdhhbD9N/9EWuqs=
