[package]

name = "nickel"
version = "0.5.0"
authors = [ "Christoph Burgdorf <christoph@thoughtram.io>",
            "Kevin Butler <haqkrs@gmail.com>",
            "Simon Persson <simon@flaskpost.org>" ]
description = "An express.js inspired web framework"
license = "MIT"

repository = "https://github.com/nickel-org/nickel.rs"
readme = "README.md"
keywords = ["nickel", "server", "web", "express"]

[features]
unstable = ["hyper/nightly", "compiletest_rs"]

[dependencies]
url = "*"
time = "*"
typemap = "*"
plugin = "*"
regex = "*"
rustc-serialize = "*"
log = "*"
hyper = "~0.5"
#hyper = "*"
groupable = "*"
mustache = "*"
lazy_static = "*"
modifier = "*"

[dependencies.compiletest_rs]
version = "*"
optional = true

[[example]]

name = "example"
path = "examples/example.rs"

[[example]]

name = "example_with_default_router"
path = "examples/example_with_default_router.rs"

[[example]]

name = "example_template"
path = "examples/example_template.rs"

[[example]]

name = "macro_example"
path = "examples/macro_example.rs"

[[example]]

name = "hello_world"
path = "examples/hello_world.rs"

[[example]]

name = "example_route_data"
path = "examples/example_route_data.rs"
