[package]

name = "nickel"
version = "0.1.0"
authors = [ "christoph@thoughtram.io" ]

[[lib]]

name = "nickel"
path = "src/lib.rs"

[dependencies.http]

git = "https://github.com/chris-morgan/rust-http.git"

[dependencies.anymap]

git = "https://github.com/chris-morgan/anymap.git"

[[example]]

name = "example"
path = "examples/example.rs"
